version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: spiritual_trend_backend
    restart: always
    env_file:
      - ./Backend/.env
    environment:
      - MONGO_URI=mongodb://spiritual_trend_mongodb:27017/spiritual-trend
    ports:
      - "127.0.0.1:5080:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - uploads_data:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: spiritual_trend_frontend
    restart: always
    ports:
      - "127.0.0.1:5083:80"
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  admin_frontend:
    build:
      context: ./admin/frontend
      dockerfile: Dockerfile
    container_name: spiritual_trend_admin_frontend
    restart: always
    ports:
      - "127.0.0.1:5084:80"
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  uploads_data:
    driver: local
