version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: spiritual_trend_backend
    restart: always
    env_file:
      - ./Backend/.env
    ports:
      - "5000:5000"
    volumes:
      - uploads_data:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: spiritual_trend_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  admin_frontend:
    build:
      context: ./admin/frontend
      dockerfile: Dockerfile
    container_name: spiritual_trend_admin_frontend
    restart: always
    ports:
      - "5174:80"
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  uploads_data:
    driver: local
