version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: spiritual_trend_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: spiritual_trend_backend
    restart: always
    depends_on:
      - mongodb
    env_file:
      - ./Backend/.env
    environment:
      - MONGO_URI=mongodb://spiritual_trend_mongodb:27017/spiritual-trend
    ports:
      - "127.0.0.1:5080:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - uploads_data:/app/uploads
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: spiritual_trend_frontend
    restart: always
    ports:
      - "127.0.0.1:5083:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  admin_frontend:
    build:
      context: ./admin/frontend
      dockerfile: Dockerfile
    container_name: spiritual_trend_admin_frontend
    restart: always
    ports:
      - "127.0.0.1:5084:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  uploads_data:
    driver: local
  mongo_data:
    driver: local

